### ISSUE TITLE
Timeout cannot be cleared

### ISSUE THREAD

**Issue by jescalan** [Richienb/timeout-signal#1]
**Describe the bug**
This library creates a timeout, but if the request is completed, the timeout remains and is not cleared. This makes using it with any sort of automated testing very difficult, as it will hang the process for as long as you have set the timeout.

**Expected behavior**
Ideally, the timeout would be automatically cleared when the request is completed, but at very least there should be some way for the user to access the [timeout id](https://github.com/node-fetch/timeout-signal/blob/master/index.js#L12) so they can manually clear it after a successful request.

**Comment by Richienb** [comment]
@jescalan I think the cleanest way to do this is to add a `timeoutSignal.clear()` function like so:

```js
const timeoutSignal = require("timeout-signal")

const signal = timeoutSignal(5000)

timeoutSignal.clear(signal)
```

What do you think?

**Comment by jescalan** [comment]
That sounds fine to me!
