### ISSUE TITLE
Use built-in AbortController when possible

### ISSUE THREAD

**Issue by jimmywarting** [Richienb/timeout-signal#2]
Node have shipped AbortController, use it first if available?

**Comment by Richienb** [comment]
We will begin using the `AbortController` built-in when Node.js 14 is EOL (30th of April 2023) or `node-fetch` requires Node.js 16.

**Comment by anentropic** [comment]
isn't `AbortController` in nodejs 14?

https://nodejs.org/docs/latest-v14.x/api/globals.html

**Comment by anentropic** [comment]
nope... it's only available if running with `--experimental-abortcontroller` flag, so the dependency is needed for now
